### PR TITLE
Updated keras and opencv keras snippets attempt 2

### PR DESCRIPTION
**Pull request by sryu1**
Hopefully this works @HalfdanJ

### CODE REVIEW

**Comment by HalfdanJ** [comment]
Hi @sryu1 , sorry for being unresponsive, travel has prevented me from working on on teachable machine, and will also be prevented the coming week over Thanksgiving. 

/gcbrun

**Comment by HalfdanJ** [comment]
To run linter locally, cd to snippets and run "npm i" "npm run lint" with nodejs installed.

**Comment by sryu1** [comment]
@HalfdanJ could you pls merge this now?

**Comment by sryu1** [comment]
@HalfdanJ ?

**Comment by sryu1** [comment]
@HalfdanJ might it be possible if I get collaborator permissions just for this repository so I can manage things when you are away?

**Pull request merged**
