### PR TITLE
Android tflite instructions update

### PR DESCRIPTION
**Pull request by natowi**
Android tflite instructions update
https://github.com/googlecreativelab/teachablemachine-community/issues/116

### CODE REVIEW

**Comment by natowi** [comment]
@googlebot I signed it!

(However I would have preferred to sign it using Github as it is possible with the Microsoft CLA)

**Comment by HalfdanJ** [comment]
/gcbrun

Thanks @natowi a lot for this! I was able to follow the steps and was able to make the app run. I went ahead and simplified some of the steps a bit. Please take a look and let me know if you have any concerns with that!

**Comment by natowi** [comment]
@HalfdanJ LGTM

**Comment by natowi** [comment]
Overwriting the labels.txt caused some issues with my build, that´s why I changed it to mylabels.txt

**Comment by HalfdanJ** [comment]
I changed it to be in a subfolder so its not overwritten, do you think that solves it?

**Comment by natowi** [comment]
I see, _assets/converted_tflite_quantized/.._ yes, that should work.

**Pull request merged**
