### PR TITLE
Updated keras and opencv keras snippets

### PR DESCRIPTION
**Pull request by sryu1**

### CODE REVIEW

**Comment by sryu1** [comment]
@HalfdanJ please.

**Comment by HalfdanJ** [comment]
Thanks for making these changes. The content looks good, but can you make sure to run the markdown linter so the test passes

**Comment by sryu1** [comment]
Sorry, I'm not sure how to run that... How do you run it?

**Comment by sryu1** [comment]
It seems like there isn't any markdown linting issues, only MD401 rule is broken...

**Comment by sryu1** [comment]
@HalfdanJ ?

**Comment by sryu1** [comment]
@HalfdanJ Would you like me to open a pull request that slowly bit by bit phases in what this pull request is supposed to be?

**Pull request closed without merging**
