### PR TITLE
Adding ml5 flipVideo() function

### PR DESCRIPTION
**Pull request by shiffman**
@irealva this should take care of flipping the video! (I cover this in my video tutorials also). @joeyklee could you double-check this?

### CODE REVIEW

**Comment by shiffman** [comment]
@googlebot I signed it!

**Comment by shiffman** [comment]
Ah, yes, thank you @joeyklee fixed this now!

**Comment by irealva** [comment]
Hi @joeyklee ! for some reason I'm seeing this run super super slow when I try on jsfiddle and I also don't see it flipped. is it me?

**Comment by joeyklee** [comment]
> Hi @joeyklee ! for some reason I'm seeing this run super super slow when I try on jsfiddle and I also don't see it flipped. is it me?

Oh! Let me check as well. One min.

**Comment by joeyklee** [comment]
@irealva - Does this run slow on your end? https://editor.p5js.org/joeyklee/sketches/ytmReYPto 
I think it is running alright on my side. 

* If you cover the webcam with your finger, you'll get `nighttime`
* otherwise: it will show daytime.

**Comment by irealva** [comment]
My bad, snippet looks fine. I was copying some extra lines that flipped the video back.

What seems to be missing is:

1. a link from the snippet to the right editor.p5.js file. Take a look at the text we added on top of this one, you could do the same if you wanted. https://raw.githubusercontent.com/googlecreativelab/teachablemachine-community/master/snippets/markdown/image/tensorflowjs/javascript.md

2. a fix in the editor.p5.js file to use the new model URLs like: https://teachablemachine.withgoogle.com/models/HN9AsmOl/

**Comment by irealva** [comment]
My bad, snippet looks fine. I was copying some extra lines that flipped the video back.

What seems to be missing is:

1. a link from the snippet to the right editor.p5.js file. Take a look at the text we added on top of this one, you could do the same if you wanted. https://raw.githubusercontent.com/googlecreativelab/teachablemachine-community/master/snippets/markdown/image/tensorflowjs/javascript.md

2. a fix in the editor.p5.js file to use the new model URLs like: https://teachablemachine.withgoogle.com/models/HN9AsmOl/

**Comment by joeyklee** [comment]
> a link from the snippet to the right editor.p5.js file. Take a look at the text we added on top of this one, you could do the same if you wanted. https://raw.githubusercontent.com/googlecreativelab/teachablemachine-community/master/snippets/markdown/image/tensorflowjs/javascript.md

@shiffman  - we should add a URL to:

For Image Classification
```
Learn more about how to use the code snippet on [github](https://github.com/ml5js/ml5-examples/blob/release/p5js/TeachableMachine/ImageModel_TM).
```

For Sound Classification
```
Learn more about how to use the code snippet on [github](https://github.com/ml5js/ml5-examples/tree/release/p5js/TeachableMachine/SoundModel_TM).
```

If the `CodingTrain` videos are ready, might we also consider linking to those? 

***

> a fix in the editor.p5.js file to use the new model URLs like: https://teachablemachine.withgoogle.com/models/HN9AsmOl/

Yes! @shiffman - let's update those URLs now.

**Comment by joeyklee** [comment]
@irealva - the model urls in the teachable machine ml5 examples should now be updated with the latest URL: https://github.com/ml5js/ml5-examples/pull/231

**Comment by shiffman** [comment]
Ok, I've now added the p5 web editor links with https://github.com/googlecreativelab/teachablemachine-community/pull/21/commits/fcbd596eb8aeb7f07f6d5fd30a3229269fef0bec. The web editor examples require a separate script to run to be updated but we'll make sure to do that before Thursday!

**Comment by joeyklee** [comment]
Re p5 web editor:
@shiffman - actually I went in and manually updated those sketches in the p5 web editor with the new teachable machine URLS. 

We will need to re run the sketch updater script once we release `0.4.2`

**Comment by irealva** [comment]
Looks good, feel free to open a new PR if you ever need to edit or add the video links.

**Comment by shiffman** [comment]
Great! This PR was merged into #20 but that one was closed, is that what you meant to do? (Sorry if I pull requested to the wrong branch!)

**Pull request merged**
