### PR TITLE
Update opencv-keras.md

### PR DESCRIPTION
**Pull request by leeyunjai82**

### CODE REVIEW

**Comment by sryu1** [comment]
@leeyunjai82, Could you try making the Google CLA check again for your agreement?

**Comment by leeyunjai82** [comment]
It looks like you've already signed this CLA.
Anything more to do?

**Comment by sryu1** [comment]
Nonono, I mean make the CLA check if you've signed it again.

**Comment by HalfdanJ** [comment]
Hi @leeyunjai82 , it looks like numpy is required in this snippet, there are multiple places where its used, for example `np.asarray`

**Comment by leeyunjai82** [comment]
I'm sorry, that is my fault.

Thanks.

**Comment by HalfdanJ** [comment]
Ah was blind. 

/gcbrun

**Pull request merged**
